cache:
  key: "${CI_BUILD_REF_NAME} node:10-alpine"
  paths:
  - node_modules/

stages:
  - test
  - build

build:
  stage: build
  image: docker:latest
  only:
    - "releases/staging"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - "docker info"
    - "docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD"
  script:
    - "docker build -t ${REGISTRY_USER}/${DOCKER_NAMESPACE}.${CI_PROJECT_NAME}:staging ."
    - "docker push ${REGISTRY_USER}/${DOCKER_NAMESPACE}.${CI_PROJECT_NAME}:staging"
  after_script:
    - "docker logout"
